FROM debian:buster
RUN apt-get update && apt-get install -y mariadb-server
COPY ./includes/script.sh ./script.sh
RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
RUN chmod +x ./script.sh
#ENTRYPOINT ["./script.sh"]
