FROM debian:buster
RUN	apt-get update && apt-get upgrade -y && \
	apt-get install mariadb-server -y
RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/script.sh /script.sh
RUN chmod +x script.sh
ENTRYPOINT ["./script.sh"]