FROM debian:buster
RUN apt-get update && apt-get install -y mariadb-server
COPY ./includes/script.sh ./script.sh
COPY includes/50-server.conf /etc/mysql/my.cnf
RUN chmod +x ./script.sh
CMD ["./script.sh"]