FROM debian:buster
RUN apt-get update && apt-get install php-fpm php-mysql mariadb-client wget vim -y
COPY ./includes/script.sh /script.sh
COPY ./includes/wp.conf /etc/php/7.3/fpm/pool.d/wwww.conf
COPY ./includes/wp-config.php /wp-config.php
RUN chmod +x script.sh
EXPOSE 9000
CMD ["sh", "script.sh"]